apiVersion: v1
kind: Service
metadata:
  name: a-service
  labels:
    app: a-service
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: a-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: a-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: a-service
        version: v1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
      - name: a-service
        image: lreimer/alphabet-service:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        # we can not use livenessProbe and readinessProbe with mutual TLS
