version: "3"

services:

  jwt-authz-service:
    build:
      context: .
    image: jwt-authz-service:1.0.1
    ports:
    - "8080:8080"
    networks:
    - jee8net

networks:
  jee8net:
    driver: bridge
