apiVersion: v1
kind: Service
metadata:
  name: javaee8-service
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: javaee8-service
  type: LoadBalancer
