apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: javaee8-service
  name: javaee8-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: javaee8-service
    spec:
      containers:
      - image: javaee8-service:1.0
        name: javaee8-service
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 640Mi
          requests:
            memory: 640Mi
      restartPolicy: Always
