apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres-db
  name: postgres-db
spec:
  ports:
  - name: "jdbc"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgres-db
  type: NodePort
