apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: secrets-service
  name: secrets-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: secrets-service
    spec:
      containers:
      - image: secrets-service:1.0.1
        name: secrets-service
        ports:
        - containerPort: 8080
        # injecting secrets as ENV variables
        env:
        - name: ENV_USER_NAME
          valueFrom:
            secretKeyRef:
              name: super-secret
              key: secret.user.name
        - name: ENV_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: super-secret
              key: secret.user.password
        # injecting secrets as files in a directory
        volumeMounts:
        - mountPath: /secrets
          name: super-secret
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: super-secret
        secret:
          secretName: super-secret
