version: "3"

services:
  secrets-service:
    build:
      context: .
    image: secrets-service:1.0.1
    ports:
    - "8080:8080"
    environment:
    - ENV_USER_NAME
    - ENV_USER_PASSWORD
    volumes:
    - ./src/test/resources:/secrets:ro
    networks:
    - jee8net
    labels:
      kompose.service.type: loadbalancer
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 640M
        reservations:
          memory: 640M

networks:
  jee8net:
    driver: bridge
